- name: demo on loops
  hosts: localhost
  tasks:
  - name: print fruit name
    ansible.builtin.debug:
     msg: name of fruit = {{item}}
  loop:
    - apple
    - banana
    - jack fruit
    - mango